config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :sendgrid_mail do
		collection do
   		get :document
    end
 	end 
 	resources :sendgrid_devise do
		collection do
   		get :document
   		get :home
    end
 	end
  #devise_for :users

  devise_for :users, path: "user", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' },:controllers => { :omniauth_callbacks => "omniauth_callbacks" , :sendgrid_devise => "sendgrid_devise" } do
     get '/user/auth/:provider' => 'omniauth_callbacks#passthru'
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def client_mail
    user = self
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = tUser.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        fullname = data['name'].split(' ')
        first_name, last_name = fullname[0], fullname[1]
        user = User.create(
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          encrypted_password: Devise.friendly_token[0,20],
        )
      end
    end
  end

  def self.create_or_fetch_google_user(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        fullname = data['name'].split(' ')
        first_name, last_name = fullname[0], fullname[1]
        user = User.create(email: data["email"],
          provider:access_token.provider,
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20],
        )
      end
    end
  end

  def self.create_or_fetch_fb_user(auth)
      email = auth.info.email
      names = auth.info.name.split(' ')
      if names.size > 1
        first_name = names[0..-2].join(' ')
        last_name = names[-2]
      else
        first_name = auth.info.name
        last_name = ''
      end

      # Check if the user with this email id has previously registered using our registered form or with google
      # If so, just convert the user to facebook user
      user = User.where(email: email).first
      if user
        case user.provider
        when nil
          user.provider = auth.provider
          user.uid = auth.uid
        when "facebook"
          if user.uid == auth.uid
            user.email = email
          else
            user.uid = auth.uid
          end
        when "google"
          user.provider = auth.provider
          user.uid = auth.uid
        end
      else
        # The user doesn't exist. 
        # So create a new user with provider = "facebook" and with fb uid
        user = User.new
        user.email = email
        user.encrypted_password = Devise.friendly_token[0,20]
        user.provider = auth.provider
        user.uid = auth.uid
      end

      # Setting Defaults
      
      # Saving the User (This will update the user first name and last name in case if the user has changed it in facebook)
      user.save
      
      # user = ClientUser.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      #   user.email = email
      #   user.password = Devise.friendly_token[0,20] unless user.password
      #   user.first_name = first_name
      #   user.last_name = last_name
      #   user.mobile_number = '' unless user.mobile_number
      #   user.organisation = ''
      #   user.country = ''
      #   # TODO - Copy Image to Avatar Later
      #   #user.image = auth.info.image # assuming the user model has an image
      # end
      return user

    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protected
	def after_sign_in_path_for(resource)
   home_sendgrid_devise_index_path
  end

  def after_sign_out_path_for(resource)
    sendgrid_devise_index_path
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout 'home'

	def index	
  	@page_title = "Home"
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	
	 def facebook
      @user = User.create_or_fetch_fb_user(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
    
    def google_oauth2
     
      @user = User.create_or_fetch_google_user(request.env["omniauth.auth"])
 
      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
    
    def failure
      redirect_to root_path
    end

  end

app/controllers/sendgrid_devise_controller.rb
class SendgridDeviseController < ApplicationController
  layout 'sendgrid_devise'

	def index
  	@page_title = "Devise -Sendgrid Mailer"	
	end

	def home
	end

end

app/controllers/sendgrid_mail_controller.rb
class SendgridMailController < ApplicationController
  layout 'sendgrid_mail'

	def index
  	@page_title = "Sendgrid Mailer"	
	end

	def document
	end

	def new
    @email=Email.new
	end
	
	def create
		get_email
		send_welcome_email
		flash[:notice] = 'Email sent successfully ! Please Check Your Email Account '
		redirect_to new_sendgrid_mail_path
  end

	def get_mail
		get_params	
	end

	private
	def email_params
    params.require(:email).permit(:email)
	end

	def get_email
		@user=Email.new(email_params)
    @user_email=email_params[:email]
	end

	def send_welcome_email
    SendgridMailerNotification.send_welcome_email(@user_email).deliver
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="center">
	<div class="card">
	  <h5 class="card-header"><b>SYLLABUS</b></h5>
	  <div class="card-body">
	    <h5 class="card-title">1. Mail Functionality Integration</h5>
	    <%= link_to "I. Using SendGrid (SendGrid_Mail)", sendgrid_mail_index_path %><br>
	    <%= link_to "II. Devise Using SendGrid (SendGrid_Mail)", sendgrid_devise_index_path %><br>
 	    <a href="#" >III. Using SES (SES_Mail)</a><br><br>

 	    <h5 class="card-title">2. Image Upload</h5>
	    <a href="#">I. Single Image Upload</a><br>
 	    <a href="#">II. Multiple Image Upload</a><br>
	  </div>
	</div>
</div>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleProject- Devise_Sendgrid_Mailer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #FDEDEC;">
    <%= render partial: 'layouts/sendgrid_devise/header' %>

    <%= yield %>

    <%= render partial: 'layouts/sendgrid_devise/footer' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "SampleProject" -%></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:  #CCD1D1;">
    <%= render partial: 'layouts/home/header' %>

    <%= yield %>

    <%= render partial: 'layouts/home/footer' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/home/_header.html.erb
<nav class="navbar" style="background-color: black; ">
  <a class="navbar-brand navbar-light mx-auto" href="#" style="align-content: center; color: #ffffff;">SAMPLE CODING</a>
</nav>

app/views/layouts/sendgrid_devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "SampleProject" -%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #FDEDEC;">
    <%= render partial: 'layouts/sendgrid_devise/header' %>

    <%= yield %>

    <%= render partial: 'layouts/sendgrid_devise/footer' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/sendgrid_devise/_footer.html.erb
<div class="footer">
  <p>© 2020 Copyright:</p>
</div>

app/views/layouts/sendgrid_devise/_header.html.erb
<nav class="navbar" style="background-color: black; ">
  <a class="navbar-brand navbar-light mx-auto" href="#" style="align-content: center; color: #ffffff;">Devise Using Sendgrid Mailer</a>
</nav>

app/views/layouts/sendgrid_mail.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "SampleProject" -%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #FDEDEC;">
    <%= render partial: 'layouts/sendgrid_mail/header' %>

    <%= yield %>

    <%= render partial: 'layouts/sendgrid_mail/footer' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/sendgrid_mail/_header.html.erb
<nav class="navbar" style="background-color: black; ">
  <a class="navbar-brand navbar-light mx-auto" href="#" style="align-content: center; color: #ffffff;">Sendgrid Mailer</a>
</nav>

app/views/sendgrid_devise/home.html.erb
<h1>WELCOME <%= @email %></h1>
<%= link_to "Logout", destroy_user_session_path , method: :delete %><br>

app/views/sendgrid_devise/index.html.erb
<br><div class="box">
	<div class="center-align">
		<div class="card">
		  <div class="card-header">
		    Devise Using SendGrid Mail
		  </div>
		  <div class="card-body">
		    <blockquote class="blockquote mb-0">
		    <%= link_to "I. Get Document", document_sendgrid_devise_index_path %><br>
		    <%= link_to "2. View Application", new_user_session_path %><br>
		    <%#= link_to "Logout", destroy_user_session_path , method: :delete %><br>
		      
		    </blockquote>
		  </div>
		</div>
		<div class="card-footer">
      <%= link_to "Back", root_path %>
    </div>
	</div>
</div>

app/views/sendgrid_mail/document.html.erb
<%= link_to "Back", sendgrid_mail_index_path %>

<div class="center" style="border-width: 3px;">
	<h2><b>Email sending using SENDGRID</b></h2>
	<div class="container" style="border-color: black;">
		<p> 	SendGrid is a cloud-based SMTP provider that allows you to send email without having to maintain email servers.SendGrid manages all of the technical details, from scaling the infrastructure to ISP outreach and reputation monitoring to whitelist services and real time analytics.</p>
	 
	    <p> * Step 1:
	          
	          Create an accout in https://app.sendgrid.com/<br>
	      
	     * Step 2:
	        
	          Signin to the created account.<br>
	      
	     * Step 3:
	        
	          Create an API key – 
	   		settings -> create Api -> Add   : Key Name, 
	                                      		 Select : Restricted Address , 
	                                 		            Allow: API keys, Alerts, Email Activity, Mail send, Mail 						settings,  Trakings<br>
	                                 		            Verifications- 2 types
	                1. Sender Authentication
	                      go to accout-> settings -> sender authentication -> create new sender -> fill up     	    the form -> verify the sender’s email.
	                2. Domain authentication
	                      go to account -> settings ->Domain authentication .<br>
	      
	     * Step 4:
	            
	           Add gem ‘sendgrid-ruby’-> 
	           bundle install.<br>
	      
	     * Step 5:
	        
				   Generate Mailer  user_mailer_notification.rb
			     // user_mailer_notification.rb
			        class UserMailerNotification < ApplicationMailer
				def send_welcome_email(user)
			   		@client_user = user
			   		mail( :to => @client_user.email,
			    			:subject => 'Thanks for signing up for our amazing ITS app' )
			 	 end
			 	 def send_forgot_password(user)
			    		 @client_user = user
			   		mail( :to => @client_user.email,
			    			:subject => 'ITS-Reset Your Password' )
			 	 end
			    end

	     * Step 6 :
	         Create template view in app/views/ send_welcome_email.html.erb
		    // send_welcome_email.html.erb
		       
			<h6>Thanks for signing up !</h6>
			<p>Thanks for joining and have a great day! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			<hr>
			<p>© ITS. 1801 California St., Suite 500, Denver, CO 80202 USA</p>
		

	         
	     * Step 7:
	           
	         Call the method after sign up from user model
			   //user.rb
			     
			  after_create :send_welcome_email
			 
			  # ----------------
			  # Instance Methods
			  # ----------------
			  def send_welcome_email
			    UserMailerNotification.send_welcome_email(self).deliver
			  end<br>

		* Step 8 :
			  Configure Environment
				   In config/environment.rbs pecify your ActionMailer settings to point to SendGrid's servers.
				//   environment.rb
				  ActionMailer::Base.smtp_settings = {
				  :user_name => 'apikey',
				  #:password => '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',
				  :password => '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',
				  #:password => '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',
				  #:domain => '',
				  :address => 'smtp.sendgrid.net',
				  :port => 587,
				  :authentication => :plain,
				  :enable_starttls_auto => true
				}
				(authnticated mail in sendgrid should same in mailer)<br>


	      Reference : 
	      
	    • https://www.youtube.com/watch?v=VQ2dGcfLIew<br>
	    • https://github.com/sendgrid/sendgrid-php/issues/181<br>
	    • https://github.com/sendgrid/sendgrid-ruby<br>
	    • https://sendgrid.com/docs/for-developers/sending-email/rubyonrails/<br><br>
	  </p>
	</div>
</div>

app/views/sendgrid_mail/index.html.erb
<br><div class="box">
	<div class="center-align">
		<div class="card">
		  <div class="card-header">
		    SendGrid Mail
		  </div>
		  <div class="card-body">
		    <blockquote class="blockquote mb-0">
		    <%= link_to "I. Get Document", document_sendgrid_mail_index_path %><br>
		    <%= link_to "2. View Application", new_sendgrid_mail_path %><br>
		      
		    </blockquote>
		  </div>
		</div>
		<div class="card-footer">
      <%= link_to "Back", root_path %>
    </div>
	</div>
</div>

app/views/sendgrid_mail/new.html.erb
<div class="layout">
  <div class="card">
    <div class="card-header">
      Type your Email Id
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <%= form_for @email, :url => { :action => "create" } do |f| %>
          <div class="form-row">
            <div class="col">
              <%= f.text_field :email, :class => "form-control", :placeholder => "Email" %>
            </div>
            <div class="col">
              <%= f.submit "Send Mail", :class => "btn btn-primary"  %>
            </div>
          </div>
        <% end %>
        <p id="notice" class="p-class"><%= notice %></p>

      </blockquote>
    </div>
    <div class="card-footer">
      <%= link_to "Back", sendgrid_mail_index_path %>
    </div>
  </div>
</div>

app/views/sendgrid_mailer_notification/send_welcome_email.html.erb
<center>
	<h2 style="margin-bottom: 15px;">Hi <%=@email%> Thanks for signing up !</h2>
	<p>Thanks for joining and have a great day! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	<hr>
	<p>© RS. E52, Shama Tower, Sheikh Zayed Road, Dubai, UAE</p>
</center>